---
- name: Copy welcome message to Apache Web Servers in AWS
  remote_user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
    
  tasks:
  - name: Copy Welcome Message to Hosts
    git: repo=https://github.com/toburke1/AWS/cpwelcome.html dest=/var/www/html
