---
- name: Creating EC2 Image Launcher
  hosts: localhost
  connection: local
  tasks:
  - name: Launching EC2
    ec2:
      instance_type: t2.micro
      key_name: ansible-skylight-ncal
      image: ami-00fc224d9834053d6
      region: us-west-1
      group: default
      count: 1
      vpc_subnet_id: subnet-09b508a86e6e78ffc
      wait: yes
      assign_public_ip: yes
      
