---
- name: register rhel hosts
  hosts: localhost
  connection: local
  gather_facts: False
  become: True
  tasks:
  - name: Register a user with password and specific pool id
    redhat_subscription:
      state: present
      username: "{{ username }}"
      password: "{{ password }}"
      pool_ids: "{{ poolid }}"
    
